import { Button, Flex, Heading, Input, Spinner, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | undefined>(undefined);

  const [result, setResult] = useState<string | undefined>(undefined);

  const [name, setName] = useState("");

  const callApi = useCallback(async () => {
    console.log("callApi called");

    if (loading) {
      return;
    }

    setLoading(true);

    const response = await fetch("/api/hello", {
      body: JSON.stringify({ name }),
      method: "POST",
    });

    if (!response.ok) {
      console.error("response not ok", response.status);
    }

    const json = await response.json();

    setResult(json.name);
    setLoading(false);
  }, [loading, name]);

  return (
    <Flex p={8}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex flexDir={"column"} color="white" gridGap={"8px"}>
          <Text color={"white"}>{result}</Text>
          {result !== "" ? (
            <>
              <Text fontSize={"2em"}>What is your name?</Text>
              <Input
                onChange={(ev) => setName(ev.target.value)}
                placeContent={"Your name"}
              ></Input>
              <Button onClick={callApi} colorScheme={"green"}>
                Say hello
              </Button>
            </>
          ) : (
            <Heading>HI {result}</Heading>
          )}
        </Flex>
      </main>
    </Flex>
  );
};

export default Home;
