import {
  Box,
  Button,
  Flex,
  Heading,
  HStack,
  Input,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { Message } from "./api/chat/history";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | undefined>(undefined);

  const [name, setName] = useState("");
  const [message, setMessage] = useState("");

  const [messages, setMessages] = useState<Message[]>([]);

  const [spawnTime, setSpawnTime] = useState(0);

  const getResults = useCallback(async () => {
    console.log("callApi called");

    if (loading) {
      return;
    }

    setLoading(true);

    const response = await fetch("/api/chat/history");

    if (!response.ok) {
      console.error("response not ok", response.status);
    }

    const json = await response.json();
    const history = json.chatHistory;

    const spawn = json.spawnTime;

    setSpawnTime(spawn);
    setMessages(history);
    setLoading(false);
  }, [loading]);

  const sendMessage = useCallback(async () => {
    const response = await fetch("/api/chat/sendMessage", {
      body: JSON.stringify({ username: name, message }),
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      console.error("response not ok", response.status);
    }
    console.log("we said hello!");

    setMessage("");

    getResults();
  }, [getResults, message, name]);

  useEffect(() => {
    const id = setInterval(() => {
      getResults();
    }, 2000);

    return () => {
      clearInterval(id);
    };
  }, [getResults]);

  return (
    <Flex p={8} flex={1} minW="100%">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex flexDir={"column"} color="white" gridGap={"8px"} flex={1}>
          <Heading fontSize={"1.5em"}>
            The server spawned at {new Date(spawnTime).toLocaleString()}
          </Heading>

          <Flex flexDir={"column"} color="white" gridGap={"8px"} w="100%">
            <HStack alignItems={"center"} w="100%">
              <Text fontSize={"1em"}>Username</Text>
              <Input
                onChange={(ev) => setName(ev.target.value)}
                placeContent={"Your name"}
              ></Input>
            </HStack>

            <HStack>
              <Text fontSize={"1em"}>Message</Text>

              <Input
                onChange={(ev) => setMessage(ev.target.value)}
                placeContent={"message"}
                w="100%"
                onKeyDown={(ev) => {
                  if (ev.key === "Enter") {
                    sendMessage();
                  }
                }}
                value={message}
              ></Input>
            </HStack>
          </Flex>

          <Box>
            {messages.map(({ message, name, time }) => {
              return (
                <Flex
                  key={name}
                  flexDir={"column"}
                  gridGap={"8px"}
                  fontSize={`12px`}
                  border="1px white solid"
                  p={4}
                  my={4}
                >
                  <Text>
                    {name} - {time}
                  </Text>
                  <Text>{message}</Text>
                </Flex>
              );
            })}
          </Box>
        </Flex>
      </main>
    </Flex>
  );
};

export default Home;
