version: "3.5"
services:
  db:
    image: "postgres"
    restart: always
    container_name: chat-app
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 8009:5432

  hasura:
    image: "hasura/graphql-engine:v2.11.2"
    expose:
      - "8082"
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@chat-app:5432/postgres
      - HASURA_GRAPHQL_ADMIN_SECRET=password
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - PORT=8080

volumes:
  database-data:
